name: TestProject

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Upload_repo:
    runs-on: ubuntu-latest

    steps:
      - name: Upload repository
        uses: actions/checkout@v2

      - name: Setup
        run: make setup

      - name: Lint
        run: make lint

      - name: Execute tests via PHPUnit
        run: make test_phpunit
